services:
  # frontend service (vite)
  viteapp:
    container_name: viteapp
    image: vite:1.0.0
    build:
      context: ./frontend
      dockerfile: vite.dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://18.212.34.41/:4000
    depends_on:
      - flaskapp


  # flask service
  flaskapp:
    container_name: flaskapp
    image: flaskapp:1.0.0
    build:
      context: ./backend
      dockerfile: flask.dockerfile
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db

# db service
  db:
    container_name: db
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
  node_modules: {}

networks:
  app-network:
    driver: bridge